### PR TITLE
[console] Role improvements. Fix #3729 

### LINKED ISSUE #3729: [role:delete] enhancement
### Issue title

1) Role delete command doesn't validate passed role names
2) When we remove the role, it would be nice to have a confirmation.

### Problem/Motivation
We will improve user experience and avoid the errors.

### How to reproduce
Try to enter a fake role name

`drupal role:delete dgdfg`

**Details to include:**
Console verion: 1.5.0

### PR DESCRIPTION
**Pull request by LOBsTerr**
1) Improve validation of the roles
2) Add confirmation
3) Rename ConfirmGeneration to generic ConfirmOperation

### CODE REVIEW

File: src/Command/Shared/ConfirmationTrait.php [hunk 1]
```diff
@@ -18,7 +18,7 @@
      *
      * @return bool
      */
-    public function confirmGeneration()
+    public function confirmOperation()
```
Comment (jmolivas) [inline src/Command/Shared/ConfirmationTrait.php]: @LOBsTerr could we add this method to avoid breaking contrib modules using it
```
    /**
     * @deprecated
     */
    public function confirmGeneration()
    {
        return  $$this->confirmOperation();
    }
```

Comment (LOBsTerr) [reply src/Command/Shared/ConfirmationTrait.php]: Yes, it is true. I will do it

Comment (jmolivas) [reply src/Command/Shared/ConfirmationTrait.php]: Awesome thanks

Comment (LOBsTerr) [reply src/Command/Shared/ConfirmationTrait.php]: Done
